<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CompanySetting;
use App\Models\User;

class CompanySettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get first admin user for updated_by
        $admin = User::whereHas('role', function($q) {
            $q->where('name', 'admin');
        })->first();

        $userId = $admin ? $admin->id : 1;

        // Company Profile Settings
        $companyProfileSettings = [
            // Basic Information
            [
                'setting_key' => 'company_name',
                'setting_value' => 'Brickly CRM',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'basic',
                'display_label' => 'Company Name',
                'display_order' => 1,
                'is_required' => true,
                'validation_rules' => json_encode(['required', 'string', 'max:255']),
                'help_text' => 'Enter your company name',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'company_size',
                'setting_value' => '',
                'setting_type' => 'number',
                'category' => 'company_profile',
                'group' => 'basic',
                'display_label' => 'Company Size (Employees)',
                'display_order' => 2,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'integer', 'min:1']),
                'help_text' => 'Number of employees in your company',
                'updated_by' => $userId,
            ],

            // Contact Information
            [
                'setting_key' => 'address',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'contact',
                'display_label' => 'Address',
                'display_order' => 10,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string', 'max:500']),
                'help_text' => 'Company address',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'city',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'contact',
                'display_label' => 'City',
                'display_order' => 11,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string', 'max:100']),
                'help_text' => null,
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'state',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'contact',
                'display_label' => 'State',
                'display_order' => 12,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string', 'max:100']),
                'help_text' => null,
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'pincode',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'contact',
                'display_label' => 'Pincode',
                'display_order' => 13,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string', 'max:10']),
                'help_text' => null,
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'country',
                'setting_value' => 'India',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'contact',
                'display_label' => 'Country',
                'display_order' => 14,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string', 'max:100']),
                'help_text' => null,
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'phone',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'contact',
                'display_label' => 'Phone Number',
                'display_order' => 15,
                'is_required' => true,
                'validation_rules' => json_encode(['required', 'string', 'regex:/^[0-9+\-\s()]+$/']),
                'help_text' => 'Primary contact number',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'landline',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'contact',
                'display_label' => 'Landline',
                'display_order' => 16,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string', 'max:20']),
                'help_text' => null,
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'email',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'contact',
                'display_label' => 'Email Address',
                'display_order' => 17,
                'is_required' => true,
                'validation_rules' => json_encode(['required', 'email', 'max:255']),
                'help_text' => 'Primary email address',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'website',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'contact',
                'display_label' => 'Website URL',
                'display_order' => 18,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'url', 'max:255']),
                'help_text' => 'Company website URL',
                'updated_by' => $userId,
            ],

            // Legal Information
            [
                'setting_key' => 'gst_number',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'legal',
                'display_label' => 'GST Number',
                'display_order' => 20,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string', 'regex:/^[0-9A-Z]{15}$/']),
                'help_text' => '15-character GST number',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'pan_number',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'legal',
                'display_label' => 'PAN Number',
                'display_order' => 21,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string', 'regex:/^[A-Z]{5}[0-9]{4}[A-Z]{1}$/']),
                'help_text' => '10-character PAN number',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'registration_number',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'legal',
                'display_label' => 'Registration Number',
                'display_order' => 22,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string', 'max:100']),
                'help_text' => 'Company registration number',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'tax_id',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'legal',
                'display_label' => 'Tax ID',
                'display_order' => 23,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string', 'max:100']),
                'help_text' => null,
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'cin',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'company_profile',
                'group' => 'legal',
                'display_label' => 'CIN (Company Identification Number)',
                'display_order' => 24,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string', 'max:100']),
                'help_text' => null,
                'updated_by' => $userId,
            ],
        ];

        // Branding Settings
        $brandingSettings = [
            // Color Scheme
            [
                'setting_key' => 'primary_color',
                'setting_value' => '#205A44',
                'setting_type' => 'text',
                'category' => 'branding',
                'group' => 'colors',
                'display_label' => 'Primary Color',
                'display_order' => 1,
                'is_required' => true,
                'validation_rules' => json_encode(['required', 'regex:/^#[0-9A-Fa-f]{6}$/']),
                'help_text' => 'Main brand color (hex format)',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'secondary_color',
                'setting_value' => '#063A1C',
                'setting_type' => 'text',
                'category' => 'branding',
                'group' => 'colors',
                'display_label' => 'Secondary Color',
                'display_order' => 2,
                'is_required' => true,
                'validation_rules' => json_encode(['required', 'regex:/^#[0-9A-Fa-f]{6}$/']),
                'help_text' => 'Secondary brand color (hex format)',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'accent_color',
                'setting_value' => '#15803d',
                'setting_type' => 'text',
                'category' => 'branding',
                'group' => 'colors',
                'display_label' => 'Accent Color',
                'display_order' => 3,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/']),
                'help_text' => 'Accent color for highlights',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'background_color',
                'setting_value' => '#FFFFFF',
                'setting_type' => 'text',
                'category' => 'branding',
                'group' => 'colors',
                'display_label' => 'Background Color',
                'display_order' => 4,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/']),
                'help_text' => 'Default background color',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'text_color',
                'setting_value' => '#063A1C',
                'setting_type' => 'text',
                'category' => 'branding',
                'group' => 'colors',
                'display_label' => 'Text Color',
                'display_order' => 5,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/']),
                'help_text' => 'Default text color',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'link_color',
                'setting_value' => '#205A44',
                'setting_type' => 'text',
                'category' => 'branding',
                'group' => 'colors',
                'display_label' => 'Link Color',
                'display_order' => 6,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/']),
                'help_text' => 'Color for links',
                'updated_by' => $userId,
            ],

            // Email Templates
            [
                'setting_key' => 'email_header_template',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'branding',
                'group' => 'email',
                'display_label' => 'Email Header Template',
                'display_order' => 10,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string']),
                'help_text' => 'HTML template for email header',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'email_footer_template',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'branding',
                'group' => 'email',
                'display_label' => 'Email Footer Template',
                'display_order' => 11,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string']),
                'help_text' => 'HTML template for email footer',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'email_signature_template',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'branding',
                'group' => 'email',
                'display_label' => 'Email Signature Template',
                'display_order' => 12,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string']),
                'help_text' => 'Default email signature',
                'updated_by' => $userId,
            ],

            // Color Template Settings
            [
                'setting_key' => 'color_template',
                'setting_value' => 'royal_green',
                'setting_type' => 'text',
                'category' => 'branding',
                'group' => 'colors',
                'display_label' => 'Color Template',
                'display_order' => 0,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string', 'in:royal_green,royal_blue,golden,royal_red,ocean_blue,sunset_orange,purple_royal,emerald_green,crimson_red,midnight_blue,custom']),
                'help_text' => 'Pre-made color template or custom',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'gradient_start',
                'setting_value' => '#063A1C',
                'setting_type' => 'text',
                'category' => 'branding',
                'group' => 'colors',
                'display_label' => 'Gradient Start Color',
                'display_order' => 7,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/']),
                'help_text' => 'Start color for gradient (hex format)',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'gradient_end',
                'setting_value' => '#205A44',
                'setting_type' => 'text',
                'category' => 'branding',
                'group' => 'colors',
                'display_label' => 'Gradient End Color',
                'display_order' => 8,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'regex:/^#[0-9A-Fa-f]{6}$/']),
                'help_text' => 'End color for gradient (hex format)',
                'updated_by' => $userId,
            ],
            [
                'setting_key' => 'use_gradient',
                'setting_value' => '1',
                'setting_type' => 'boolean',
                'category' => 'branding',
                'group' => 'colors',
                'display_label' => 'Use Gradient',
                'display_order' => 9,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'boolean']),
                'help_text' => 'Enable gradient colors instead of solid colors',
                'updated_by' => $userId,
            ],

            // Advanced
            [
                'setting_key' => 'custom_css',
                'setting_value' => '',
                'setting_type' => 'text',
                'category' => 'branding',
                'group' => 'advanced',
                'display_label' => 'Custom CSS',
                'display_order' => 20,
                'is_required' => false,
                'validation_rules' => json_encode(['nullable', 'string']),
                'help_text' => 'Custom CSS code for additional styling',
                'updated_by' => $userId,
            ],
        ];

        // Insert all settings
        foreach (array_merge($companyProfileSettings, $brandingSettings) as $setting) {
            CompanySetting::updateOrCreate(
                ['setting_key' => $setting['setting_key']],
                $setting
            );
        }
    }
}
