<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Meetings Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        h1 {
            color: #063A1C;
            text-align: center;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #063A1C;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <h1>Meetings Export Report</h1>
    <p><strong>Generated:</strong> {{ date('Y-m-d H:i:s') }}</p>
    <p><strong>Total Records:</strong> {{ count($meetings) }}</p>
    
    <table>
        <thead>
            <tr>
                <th>Customer Name</th>
                <th>Phone</th>
                <th>Meeting Date</th>
                <th>Status</th>
                <th>Employee</th>
                <th>Team Leader</th>
                <th>Location</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @foreach($meetings as $meeting)
                <tr>
                    <td>{{ $meeting->lead->name ?? $meeting->customer_name ?? 'N/A' }}</td>
                    <td>{{ $meeting->lead->phone ?? $meeting->phone ?? 'N/A' }}</td>
                    <td>{{ $meeting->scheduled_at ? $meeting->scheduled_at->format('Y-m-d H:i') : 'N/A' }}</td>
                    <td>{{ ucfirst($meeting->status) }}</td>
                    <td>{{ $meeting->assignedTo->name ?? $meeting->employee ?? 'N/A' }}</td>
                    <td>{{ $meeting->team_leader ?? 'N/A' }}</td>
                    <td>{{ $meeting->property_address ?? 'N/A' }}</td>
                    <td>{{ $meeting->meeting_notes ?? $meeting->feedback ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>Generated by {{ brand_name() }} - {{ date('Y') }}</p>
    </div>
</body>
</html>

