<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Prospects Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        h1 {
            color: #063A1C;
            text-align: center;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #063A1C;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <h1>Prospects Export Report</h1>
    <p><strong>Generated:</strong> {{ date('Y-m-d H:i:s') }}</p>
    <p><strong>Total Records:</strong> {{ count($prospects) }}</p>
    
    <table>
        <thead>
            <tr>
                <th>Customer Name</th>
                <th>Phone</th>
                <th>Budget</th>
                <th>Location</th>
                <th>Purpose</th>
                <th>Status</th>
                <th>Created Date</th>
                <th>Sales Executive</th>
                <th>Manager</th>
            </tr>
        </thead>
        <tbody>
            @foreach($prospects as $prospect)
                <tr>
                    <td>{{ $prospect->customer_name }}</td>
                    <td>{{ $prospect->phone }}</td>
                    <td>{{ $prospect->budget ? number_format($prospect->budget, 2) : 'N/A' }}</td>
                    <td>{{ $prospect->preferred_location ?? 'N/A' }}</td>
                    <td>{{ $prospect->purpose ?? 'N/A' }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $prospect->verification_status)) }}</td>
                    <td>{{ $prospect->created_at->format('Y-m-d H:i') }}</td>
                    <td>{{ $prospect->telecaller->name ?? 'N/A' }}</td>
                    <td>{{ $prospect->assignedManager->name ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>Generated by {{ brand_name() }} - {{ date('Y') }}</p>
    </div>
</body>
</html>

