<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Site Visits Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        h1 {
            color: #063A1C;
            text-align: center;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #063A1C;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <h1>Site Visits Export Report</h1>
    <p><strong>Generated:</strong> {{ date('Y-m-d H:i:s') }}</p>
    <p><strong>Total Records:</strong> {{ count($siteVisits) }}</p>
    
    <table>
        <thead>
            <tr>
                <th>Customer Name</th>
                <th>Phone</th>
                <th>Visit Date</th>
                <th>Visit Type</th>
                <th>Status</th>
                <th>Assigned To</th>
                <th>Closer Status</th>
                <th>Location</th>
            </tr>
        </thead>
        <tbody>
            @foreach($siteVisits as $visit)
                <tr>
                    <td>{{ $visit->lead->name ?? $visit->customer_name ?? 'N/A' }}</td>
                    <td>{{ $visit->lead->phone ?? $visit->phone ?? 'N/A' }}</td>
                    <td>{{ $visit->scheduled_at ? $visit->scheduled_at->format('Y-m-d H:i') : 'N/A' }}</td>
                    <td>{{ $visit->lead_type ?? 'N/A' }}</td>
                    <td>{{ ucfirst($visit->status) }}</td>
                    <td>{{ $visit->assignedTo->name ?? 'N/A' }}</td>
                    <td>{{ ucfirst($visit->closer_status ?? 'N/A') }}</td>
                    <td>{{ $visit->property_address ?? $visit->property_name ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>Generated by {{ brand_name() }} - {{ date('Y') }}</p>
    </div>
</body>
</html>

