<dialog class="ps-dialog" id="psCaseDialog"><div class="ps-dialog-head"><h3 id="psCaseTitle">Customer Actions</h3><button class="ps-btn" type="button" data-close-dialog><i class="fas fa-xmark"></i></button></div><div class="ps-dialog-body"><div class="ps-panel-grid">
    <button class="ps-btn primary" type="button" id="psCaseDemand"><i class="fas fa-calendar-plus"></i> Add Demand</button>
    <button class="ps-btn" type="button" id="psCasePayment"><i class="fas fa-indian-rupee-sign"></i> Record Payment / Refund</button>
    <button class="ps-btn blue" type="button" id="psCaseClaim"><i class="fas fa-building-columns"></i> Raise Builder Claim</button>
    <form method="POST" id="psActivateForm">@csrf<button class="ps-btn primary" type="submit"><i class="fas fa-play"></i> Activate Case</button></form>
</div><form method="POST" id="psCancelForm" style="margin-top:14px">@csrf<div class="ps-field"><label>Cancellation reason</label><textarea class="ps-textarea" name="reason" required minlength="5" placeholder="Reason required; history will be preserved"></textarea></div><button class="ps-btn danger" type="submit" style="margin-top:8px"><i class="fas fa-ban"></i> Cancel Case</button></form></div></dialog>

<dialog class="ps-dialog" id="psDemandDialog"><form method="POST" id="psDemandForm" data-loading>@csrf<div class="ps-dialog-head"><h3>Add Customer Demand</h3><button class="ps-btn" type="button" data-close-dialog><i class="fas fa-xmark"></i></button></div><div class="ps-dialog-body"><div class="ps-form-grid">
    <div class="ps-field wide"><label>Demand title</label><input class="ps-input" name="title" required placeholder="Initial 10% / Agreement instalment"></div>
    <div class="ps-field"><label>Amount type</label><select class="ps-select" name="amount_type"><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select></div>
    <div class="ps-field"><label>Percentage</label><input class="ps-input" name="percentage" type="number" step="0.001" min="0.001" max="100"></div>
    <div class="ps-field"><label>Fixed amount</label><input class="ps-input" name="amount" type="number" step="0.01" min="0.01"></div>
    <div class="ps-field"><label>Due rule</label><select class="ps-select" name="due_rule"><option value="fixed_date">Fixed date</option><option value="milestone">Milestone</option></select></div>
    <div class="ps-field"><label>Due date</label><input class="ps-input" name="due_date" type="date"></div>
    <div class="ps-field"><label>Milestone</label><input class="ps-input" name="milestone_name" placeholder="On agreement / slab completion"></div>
    <div class="ps-field wide"><label>Remark</label><textarea class="ps-textarea" name="remark"></textarea></div>
</div></div><div class="ps-dialog-actions"><button class="ps-btn" type="button" data-close-dialog>Cancel</button><button class="ps-btn primary" type="submit">Save Demand</button></div></form></dialog>

<dialog class="ps-dialog" id="psTransactionDialog"><form method="POST" id="psTransactionForm" enctype="multipart/form-data" data-loading>@csrf<input type="hidden" name="demand_id" id="psTransactionDemand"><div class="ps-dialog-head"><h3 id="psTransactionTitle">Record Transaction</h3><button class="ps-btn" type="button" data-close-dialog><i class="fas fa-xmark"></i></button></div><div class="ps-dialog-body"><div class="ps-form-grid">
    <div class="ps-field"><label>Type</label><select class="ps-select" name="type" required><option value="payment">Customer Payment</option><option value="refund">Refund</option><option value="reversal">Reversal</option></select></div>
    <div class="ps-field"><label>Amount</label><input class="ps-input" name="amount" type="number" step="0.01" min="0.01" required></div>
    <div class="ps-field"><label>Date</label><input class="ps-input" name="transaction_date" type="date" max="{{ now()->toDateString() }}" required></div>
    <div class="ps-field"><label>Mode</label><input class="ps-input" name="payment_mode" placeholder="Bank / UPI / Cheque"></div>
    <div class="ps-field"><label>UTR / Reference</label><input class="ps-input" name="reference_no"></div>
    <div class="ps-field"><label>Proof</label><input class="ps-input" name="proof" type="file" accept=".jpg,.jpeg,.png,.pdf,.webp"></div>
    <div class="ps-field wide"><label>Audit remark</label><textarea class="ps-textarea" name="remark" required minlength="5"></textarea></div>
</div></div><div class="ps-dialog-actions"><button class="ps-btn" type="button" data-close-dialog>Cancel</button><button class="ps-btn primary" type="submit">Save Pending Verification</button></div></form></dialog>

<dialog class="ps-dialog" id="psClaimDialog"><form method="POST" id="psClaimForm" enctype="multipart/form-data" data-loading>@csrf<div class="ps-dialog-head"><h3 id="psClaimTitle">Raise Builder Claim</h3><button class="ps-btn" type="button" data-close-dialog><i class="fas fa-xmark"></i></button></div><div class="ps-dialog-body"><div class="ps-mail-lock">Maximum fresh claimable: <strong id="psClaimMaxText"></strong></div><div class="ps-form-grid" style="margin-top:10px">
    <div class="ps-field"><label>Claim amount</label><input class="ps-input" id="psClaimAmount" name="claim_amount" type="number" step="0.01" min="0.01" required></div>
    <div class="ps-field"><label>Claim date</label><input class="ps-input" name="claim_date" type="date" value="{{ now()->toDateString() }}" required></div>
    <div class="ps-field"><label>GST</label><input class="ps-input" name="gst_amount" type="number" step="0.01" min="0" value="0"></div>
    <div class="ps-field"><label>TDS</label><input class="ps-input" name="tds_amount" type="number" step="0.01" min="0" value="0"></div>
    <div class="ps-field"><label>Expected release</label><input class="ps-input" name="expected_date" type="date"></div>
    <div class="ps-field"><label>Claim proof</label><input class="ps-input" name="proof" type="file" accept=".jpg,.jpeg,.png,.pdf,.webp"></div>
    <div class="ps-field wide"><label>Audit remark</label><textarea class="ps-textarea" name="remark" required minlength="5"></textarea></div>
</div></div><div class="ps-dialog-actions"><button class="ps-btn" type="button" data-close-dialog>Cancel</button><button class="ps-btn primary" type="submit">Raise Claim</button></div></form></dialog>

<dialog class="ps-dialog" id="psReceiptDialog"><form method="POST" id="psReceiptForm" enctype="multipart/form-data" data-loading>@csrf<div class="ps-dialog-head"><h3 id="psReceiptTitle">Builder Receipt</h3><button class="ps-btn" type="button" data-close-dialog><i class="fas fa-xmark"></i></button></div><div class="ps-dialog-body"><div class="ps-mail-lock">Maximum remaining: <strong id="psReceiptMaxText"></strong></div><div class="ps-form-grid" style="margin-top:10px">
    <div class="ps-field"><label>Received amount</label><input class="ps-input" id="psReceiptAmount" name="amount" type="number" step="0.01" min="0.01" required></div><div class="ps-field"><label>Received date</label><input class="ps-input" name="received_date" type="date" value="{{ now()->toDateString() }}" required></div><div class="ps-field"><label>Mode</label><input class="ps-input" name="payment_mode"></div><div class="ps-field"><label>Reference</label><input class="ps-input" name="reference_no"></div><div class="ps-field"><label>Proof</label><input class="ps-input" name="proof" type="file"></div><div class="ps-field wide"><label>Audit remark</label><textarea class="ps-textarea" name="remark" required minlength="5"></textarea></div>
</div></div><div class="ps-dialog-actions"><button class="ps-btn" type="button" data-close-dialog>Cancel</button><button class="ps-btn primary" type="submit">Save Receipt</button></div></form></dialog>

<dialog class="ps-dialog" id="psDocumentDialog"><form method="POST" id="psDocumentForm" enctype="multipart/form-data" data-loading>@csrf<div class="ps-dialog-head"><h3 id="psDocumentTitle">Update Document</h3><button class="ps-btn" type="button" data-close-dialog><i class="fas fa-xmark"></i></button></div><div class="ps-dialog-body"><div class="ps-form-grid"><div class="ps-field"><label>Status</label><select class="ps-select" id="psDocumentStatus" name="status">@foreach($documentStatuses as $item)<option value="{{ $item }}">{{ str($item)->headline() }}</option>@endforeach</select></div><div class="ps-field"><label>File</label><input class="ps-input" name="file" type="file"></div><div class="ps-field wide"><label>Remark</label><textarea class="ps-textarea" name="remark"></textarea></div></div></div><div class="ps-dialog-actions"><button class="ps-btn" type="button" data-close-dialog>Cancel</button><button class="ps-btn primary" type="submit">Update Document</button></div></form></dialog>

<dialog class="ps-dialog" id="psVerifyDialog"><div class="ps-dialog-head"><h3>Verify Pending Transactions</h3><button class="ps-btn" type="button" data-close-dialog><i class="fas fa-xmark"></i></button></div><div class="ps-dialog-body" id="psVerifyList"></div></dialog>

<dialog class="ps-dialog" id="psQuickProjectDialog"><form method="POST" action="{{ route('post-sales.projects.quick-store') }}" data-loading>@csrf<div class="ps-dialog-head"><h3>Add Builder / Project</h3><button class="ps-btn" type="button" data-close-dialog aria-label="Close"><i class="fas fa-xmark"></i></button></div><div class="ps-dialog-body"><div class="ps-form-grid">
    <div class="ps-field wide"><label for="psQuickProjectName">Project name</label><input class="ps-input" id="psQuickProjectName" name="project_name" required maxlength="255" placeholder="Project name"></div>
    <div class="ps-field"><label for="psQuickBuilder">Existing builder</label><select class="ps-select" id="psQuickBuilder" name="builder_id"><option value="">Select or add new</option>@foreach($builders as $builder)<option value="{{ $builder->id }}">{{ $builder->name }}</option>@endforeach</select></div>
    <div class="ps-field"><label for="psQuickBuilderName">New builder name</label><input class="ps-input" id="psQuickBuilderName" name="builder_name" maxlength="255" placeholder="Only if builder is not listed"></div>
</div><div class="ps-mail-lock" style="margin-top:10px"><i class="fas fa-circle-info"></i> Project save hone ke baad payment plan aur builder release slabs configure kar sakte hain.</div></div><div class="ps-dialog-actions"><button class="ps-btn" type="button" data-close-dialog>Cancel</button><button class="ps-btn primary" type="submit"><i class="fas fa-plus"></i> Add Project</button></div></form></dialog>
