<?php

return [
    'stages' => [
        [
            'id' => 'telecaller_lead_creation',
            'name' => 'Telecaller Lead Creation',
            'description' => 'Telecaller receives lead assignment and task',
            'requiredRoles' => ['sales_executive'],
            'order' => 1,
            'dependencies' => [],
        ],
        [
            'id' => 'prospect_creation',
            'name' => 'Prospect Creation',
            'description' => 'Telecaller marks lead as interested and creates prospect',
            'requiredRoles' => ['sales_executive'],
            'order' => 2,
            'dependencies' => ['telecaller_lead_creation'],
        ],
        [
            'id' => 'manager_verification',
            'name' => 'Manager Verification',
            'description' => 'Sales Manager receives verification task and verifies prospect',
            'requiredRoles' => ['sales_manager'],
            'order' => 3,
            'dependencies' => ['prospect_creation'],
        ],
        [
            'id' => 'meeting_creation',
            'name' => 'Meeting Creation',
            'description' => 'Sales Manager creates and completes meeting',
            'requiredRoles' => ['sales_manager'],
            'order' => 4,
            'dependencies' => ['manager_verification'],
        ],
        [
            'id' => 'meeting_verification',
            'name' => 'Meeting Verification',
            'description' => 'CRM/Admin/Sales Head verifies meeting',
            'requiredRoles' => ['admin', 'crm'],
            'order' => 5,
            'dependencies' => ['meeting_creation'],
        ],
        [
            'id' => 'site_visit_creation',
            'name' => 'Site Visit Creation',
            'description' => 'Sales Manager creates and completes site visit',
            'requiredRoles' => ['sales_manager'],
            'order' => 6,
            'dependencies' => ['meeting_verification'],
        ],
        [
            'id' => 'site_visit_verification',
            'name' => 'Site Visit Verification',
            'description' => 'CRM/Admin/Sales Head verifies site visit',
            'requiredRoles' => ['admin', 'crm'],
            'order' => 7,
            'dependencies' => ['site_visit_creation'],
        ],
        [
            'id' => 'closer_conversion',
            'name' => 'Closer Conversion',
            'description' => 'Sales Manager converts verified site visit to closer',
            'requiredRoles' => ['sales_manager'],
            'order' => 8,
            'dependencies' => ['site_visit_verification'],
        ],
        [
            'id' => 'closer_verification',
            'name' => 'Closer Verification',
            'description' => 'CRM/Admin verifies closer and updates lead status to closed',
            'requiredRoles' => ['admin', 'crm'],
            'order' => 9,
            'dependencies' => ['closer_conversion'],
        ],
        [
            'id' => 'incentive_request',
            'name' => 'Incentive Request',
            'description' => 'HR/Sales Executive/Sales Manager requests incentive for verified closer',
            'requiredRoles' => ['hr_manager', 'sales_executive', 'sales_manager'],
            'order' => 10,
            'dependencies' => ['closer_verification'],
        ],
        [
            'id' => 'incentive_approval',
            'name' => 'Incentive Approval',
            'description' => 'Finance Manager approves/rejects incentive request',
            'requiredRoles' => ['finance_manager'],
            'order' => 11,
            'dependencies' => ['incentive_request'],
        ],
    ],

    'error_types' => [
        'missing_data' => 'Missing required data',
        'invalid_status' => 'Invalid status transition',
        'missing_relationship' => 'Missing required relationship',
        'verification_issue' => 'Verification status issue',
        'database_constraint' => 'Database constraint violation',
        'missing_field' => 'Missing required field',
        'permission_denied' => 'Permission denied',
    ],

    'fix_actions' => [
        'create_record' => 'Create missing record',
        'update_status' => 'Update status value',
        'create_relationship' => 'Create missing relationship',
        'fix_data' => 'Fix data inconsistency',
        'validate_foreign_key' => 'Validate foreign key',
    ],
];
