<style>
.lad-task-section .lad-section-head{background:#fff;padding:16px 18px;min-height:68px}
.lad-task-section h2{font-size:17px;font-weight:700;color:#19382b}
#ladTaskTotals{display:flex;align-items:center;gap:22px;flex-wrap:wrap;font-size:12px;color:#566a60}
#ladTaskTotals strong{font-size:20px;font-weight:700;margin-left:7px;color:#19382b;font-variant-numeric:tabular-nums}
#ladTaskTotals .lad-total-completed strong{color:#08734a}
#ladTaskTotals .lad-total-remaining strong{color:#a44a15}
.lad-task-section .lad-summary{min-width:1180px;border-collapse:separate;border-spacing:0}
.lad-task-section .lad-summary>thead>tr>th{border:0;border-right:1px solid #438869;vertical-align:middle;text-align:center;padding:10px 8px;font-size:12px;line-height:1.4}
.lad-task-section .lad-summary>thead>tr>th:first-child{text-align:left;position:sticky;left:0;z-index:3}
.lad-column-labels{display:grid;grid-template-columns:1fr 1fr;gap:4px;margin-top:8px;padding-top:6px;border-top:1px solid #438869;color:#e1eee7;font-size:10px;font-weight:400}
.lad-task-section #ladRows>tr[id]>td{height:54px;padding:6px 8px;vertical-align:middle;border:0;border-right:1px solid #e2e9e5;border-bottom:1px solid #e2e9e5;text-align:center;background:#fff}
.lad-task-section #ladRows>tr[id]:nth-child(even)>td{background:#f7faf8}
.lad-task-section #ladRows>tr[id]:hover>td{background:#eef5f1}
.lad-task-section #ladRows>tr[id]:has([aria-expanded=true])>td{background:#eaf3fb;border-bottom-color:#b5cede}
.lad-task-section #ladRows>tr[id]>td:first-child{position:sticky;left:0;z-index:2;text-align:left}
.lad-person{display:flex;align-items:center;gap:9px;font-weight:600;line-height:1.35;font-size:13px}
.lad-person .lad-icon{flex:0 0 28px;width:28px;height:28px;background:transparent;border-color:transparent}
.lad-person .lad-icon:hover{border-color:#a9c6b5;background:#fff}
.lad-person [aria-expanded=true] i{transform:rotate(180deg)}
.lad-metrics{display:grid;grid-template-columns:1fr 1fr;gap:4px}
.lad-task-section .lad-number{width:100%;min-height:34px;padding:5px 4px;border-radius:4px;text-align:center;font-size:14px;font-weight:600;font-variant-numeric:tabular-nums;text-decoration:none;color:#244c65}
.lad-task-section .lad-number[data-bucket=done],.lad-task-section .lad-number[data-bucket=completed_today]{color:#08734a}
.lad-task-section .lad-number[data-bucket=remaining]{color:#a44a15}
.lad-task-section .lad-number.is-zero{color:#819187;font-weight:400}
.lad-task-section .lad-number:hover{background:#dcece3;box-shadow:inset 0 0 0 1px #9fbdae}
.lad-task-section button:focus-visible{outline:2px solid #1573b5;outline-offset:2px}
.lad-task-section .lad-expanded-head{font-size:13px;border-left:3px solid #377395;padding:12px 16px}
@media(max-width:650px){#ladTaskTotals{gap:12px}#ladTaskTotals strong{font-size:18px}.lad-task-section .lad-section-head{padding:12px}}
.lad-section-head{flex-wrap:wrap}
html body.sidebar-hidden #mainContent:has(.lad-page){margin-left:0!important;width:100%!important}
.lad-page{color:#12362a;font-size:13px;letter-spacing:0}.lad-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;padding:12px;background:#ecf6ef;border:1px solid #b8cfbf}
.lad-controls{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.lad-controls select,.lad-button{padding:9px 12px;min-height:40px;border:1px solid #a9c6b5;background:white;border-radius:4px;color:#145a3b;font:inherit}.lad-button{cursor:pointer}.lad-button:disabled{opacity:.5;cursor:default}.lad-button.primary{background:#166d46;color:white}
.lad-filter{display:flex;align-items:center;gap:8px}.lad-filter label{white-space:nowrap}
.lad-layout{display:grid;grid-template-columns:minmax(0,1fr);gap:20px;margin-top:20px}@media(min-width:1900px){.lad-layout{grid-template-columns:minmax(0,1fr) minmax(0,1.2fr)}}
.lad-section{min-width:0;border:1px solid #b8cfbf;background:white}.lad-section h2{font-size:17px;margin:0}.lad-section-head{padding:14px;display:flex;justify-content:space-between;gap:12px;align-items:center;background:#edf6f0;border-bottom:1px solid #b8cfbf}
.lad-counts{display:flex;border-bottom:1px solid #b8cfbf}.lad-counts>div{flex:1;padding:12px;border-right:1px solid #d5e2da}.lad-counts strong{font-size:23px;display:block}.lad-counts span{color:#526e62;font-size:12px}
.lad-scroll{overflow:auto;max-height:650px}.lad-table{width:100%;min-width:800px;border-collapse:collapse;table-layout:fixed}.lad-summary{min-width:1000px}.lad-table th{padding:10px 8px;background:#176b46;color:white;font-size:11px;text-align:left;position:sticky;top:0;z-index:1;border:1px solid #609578}.lad-table td{padding:10px 8px;border:1px solid #dce7df;vertical-align:top;overflow-wrap:anywhere}.lad-table tbody tr:nth-child(even){background:#f8fbf9}.lad-table small{display:block;color:#63776e;margin-top:4px}
.lad-number{border:0;background:none;color:#096192;cursor:pointer;text-align:left;padding:4px;min-height:28px;font:inherit;text-decoration:underline;text-underline-offset:3px}.lad-icon{width:32px;height:32px;border:1px solid #b8cfbf;border-radius:4px;background:#f3f9f5;color:#176b46;cursor:pointer}.lad-pager{padding:10px;display:flex;justify-content:space-between;align-items:center;gap:12px;border-top:1px solid #dce7df}.lad-pager>div{display:flex;gap:6px}.lad-message{padding:25px;text-align:center;color:#61786a}.lad-error{background:#fff0ee;color:#a72c24;padding:12px;border:1px solid #e9b2ac}
.lad-expand-cell{padding:0!important;background:#fff!important}.lad-expanded-head{padding:12px;background:#eaf2fa;color:#1a4c72}.lad-expanded .lad-table{min-width:750px}.lad-expanded th{background:#2c5876}
dialog.lad-dialog{position:fixed;inset:0;margin:auto;width:min(760px,calc(100vw - 24px));max-height:90dvh;overflow:hidden;padding:0;border:1px solid #a9c6b5;border-radius:6px;color:#12362a}dialog.lad-dialog[open]{display:flex;flex-direction:column}dialog.lad-dialog::backdrop{background:#102a2390}.lad-dialog header{display:flex;align-items:center;justify-content:space-between;padding:14px;background:#edf6f0;flex-shrink:0}.lad-dialog h2{font-size:18px}.lad-detail-body{min-height:0;overflow:auto;padding:16px;overscroll-behavior:contain}.lad-detail-body h3{font-size:14px;margin:16px 0 8px}.lad-detail-grid{display:grid;grid-template-columns:1fr 1fr}.lad-detail-grid>div{padding:10px;border:1px solid #dce7df;overflow-wrap:anywhere}.lad-detail-grid small{display:block;color:#627a6e}.lad-detail-grid strong{display:block;margin-top:5px}.lad-history{padding:10px;border-bottom:1px solid #dce7df;white-space:pre-wrap}
@media(max-width:650px){.lad-controls{width:100%}.lad-controls select{flex:1;min-width:0;max-width:100%}.lad-counts>div{padding:8px}.lad-detail-grid{grid-template-columns:1fr}}
@media(max-width:650px){.lad-filter{width:100%;display:grid;grid-template-columns:110px minmax(0,1fr)}.lad-filter select{width:100%}}
</style>
<div class="lad-page">
    <header class="lad-toolbar"><h1 id="auditorDashboardTitle">Dashboard</h1><div class="lad-controls"><div class="lad-filter"><label for="ladUser">Salesperson</label><select id="ladUser"><option value="">All Sales Users</option>@foreach($salesUsers as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</select></div><div class="lad-filter"><label for="ladRange">Assignment Date</label><select id="ladRange"><option value="all">All Time</option><option value="today">Today</option><option value="week">This Week</option><option value="month">This Month</option><option value="year">This Year</option></select></div><button id="ladApply" class="lad-button primary" type="button">Apply</button></div></header>
    <div id="ladError" class="lad-error" role="alert" hidden></div>
    <div class="lad-layout">
        <section class="lad-section" aria-label="Untouched Leads">
            <div class="lad-counts"><div><span>Total Untouched</span><strong id="ladTotal">-</strong></div><div><span>New Assigned</span><strong id="ladNew">-</strong></div><div><span>Fresh Transfer</span><strong id="ladTransfer">-</strong></div></div>
            <div class="lad-scroll"><table class="lad-table"><thead><tr><th>Customer</th><th>Mobile</th><th>Source</th><th>Salesperson</th><th>Assignment Type</th><th>Assigned / Transferred</th><th>Waiting Since</th><th style="width:55px">View</th></tr></thead><tbody id="ladUntouched"><tr><td colspan="8" class="lad-message">Loading...</td></tr></tbody></table></div><div id="ladUntouchedPager" class="lad-pager"></div>
        </section>
        <section class="lad-section lad-task-section"><header class="lad-section-head"><h2>Today's Task Summary</h2><span id="ladTaskTotals"></span></header>
            <div class="lad-scroll"><table class="lad-table lad-summary"><thead><tr><th style="width:220px">Salesperson</th><th scope="col">Initial Lead Tasks<div class="lad-column-labels"><span>Scheduled</span><span>Done</span></div></th><th scope="col">Follow-ups<div class="lad-column-labels"><span>Scheduled</span><span>Done</span></div></th><th scope="col">Meetings<div class="lad-column-labels"><span>Scheduled</span><span>Done</span></div></th><th scope="col">Site Visits<div class="lad-column-labels"><span>Scheduled</span><span>Done</span></div></th><th scope="col">Other Sales Tasks<div class="lad-column-labels"><span>Scheduled</span><span>Done</span></div></th><th title="All tasks scheduled for today, including completed tasks">Scheduled Today</th><th>Completed Today</th><th>Remaining</th></tr></thead><tbody id="ladRows"><tr><td colspan="9" class="lad-message">Loading...</td></tr></tbody></table></div>
        </section>
    </div>
</div>
<dialog id="ladDetails" class="lad-dialog"><header><h2>Customer Details</h2><button class="lad-icon" type="button" id="ladClose" title="Close" aria-label="Close"><i class="fas fa-times"></i></button></header><div id="ladDetailsBody" class="lad-detail-body"></div></dialog>
@push('scripts')
<script>
(() => {
    const urls = {summary:@json(route('lead-quality-auditor.dashboard.summary')),untouched:@json(route('lead-quality-auditor.dashboard.untouched')),tasks:@json(route('lead-quality-auditor.dashboard.tasks')),details:@json(route('lead-quality-auditor.dashboard.details'))};
    const categories = {initial:'Initial Lead Tasks',follow_up:'Follow-ups',meeting:'Meetings',site_visit:'Site Visits',other:'Other Sales Tasks'};
    const bucketLabels={due:'Scheduled Today',done:'Done',completed_today:'Completed Today',remaining:'Remaining'};
    const byId=id=>document.getElementById(id), esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    let appliedUser='',appliedRange='all',generation=0,serverNow=new Date(),expanded=null;
    const date=value=>value?new Date(value.includes('T')?value:value.replace(' ','T')+'+05:30').toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'}):'Unknown';
    function waiting(value){if(!value)return 'Unknown';const minutes=Math.max(0,Math.floor((serverNow-new Date(value.replace(' ','T')+'+05:30'))/60000));return minutes>=1440?`${Math.floor(minutes/1440)}d ${Math.floor(minutes%1440/60)}h`:`${Math.floor(minutes/60)}h ${minutes%60}m`;}
    async function get(url,params={}){const response=await fetch(url+'?'+new URLSearchParams(params),{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Data load nahi hua. Apply karke dobara try karein.');return response.json();}
    function pager(container,data,onPage){container.replaceChildren();const label=document.createElement('span');label.textContent=`${data.total} records · Page ${data.current_page} of ${data.last_page}`;container.append(label);const controls=document.createElement('div');for(const [label,delta] of [['Previous',-1],['Next',1]]){const b=document.createElement('button');b.type='button';b.className='lad-button';b.textContent=label;b.disabled=delta<0?data.current_page<=1:data.current_page>=data.last_page;b.onclick=()=>onPage(data.current_page+delta);controls.append(b);}container.append(controls);}
    function eye(id){return `<button type="button" class="lad-icon" data-lead="${Number(id)}" title="View customer details" aria-label="View customer details"><i class="fas fa-eye"></i></button>`;}
    async function untouched(page=1,version=generation){byId('ladUntouched').innerHTML='<tr><td colspan="8" class="lad-message">Loading...</td></tr>';byId('ladUntouchedPager').replaceChildren();try{const data=await get(urls.untouched,{user_id:appliedUser,range:appliedRange,page});if(version!==generation)return;byId('ladUntouched').innerHTML=data.data.length?data.data.map(row=>`<tr><td>${esc(row.customer)}</td><td>${esc(row.phone||'-')}</td><td>${esc(row.source||'-')}</td><td>${esc(row.salesperson)}</td><td>${row.assignment_type==='fresh_transfer'?'Fresh Transfer':'New Assigned'}</td><td>${esc(date(row.assigned_at))}</td><td>${esc(waiting(row.assigned_at))}</td><td>${eye(row.lead_id)}</td></tr>`).join(''):'<tr><td colspan="8" class="lad-message">No untouched leads.</td></tr>';pager(byId('ladUntouchedPager'),data,p=>untouched(p));}catch(error){if(version===generation)byId('ladUntouched').innerHTML=`<tr><td colspan="8" class="lad-error">${esc(error.message)}</td></tr>`;}}
    function countButton(user,bucket,count,category='',label=''){return `<button class="lad-number ${Number(count)===0?'is-zero':''}" title="${esc(categories[category]||'All tasks')} - ${esc(bucketLabels[bucket])}: ${count}" aria-label="${esc(categories[category]||'All tasks')} - ${esc(bucketLabels[bucket])}: ${count}" type="button" data-user="${user}" data-bucket="${bucket}" data-category="${category}">${esc(label)}${count}</button>`;}
    async function load(){const version=++generation;appliedUser=byId('ladUser').value;appliedRange=byId('ladRange').value;expanded=null;byId('ladError').hidden=true;byId('ladApply').disabled=true;byId('ladRows').innerHTML='<tr><td colspan="9" class="lad-message">Loading...</td></tr>';['ladTotal','ladNew','ladTransfer'].forEach(id=>byId(id).textContent='-');byId('ladTaskTotals').textContent='';try{const data=await get(urls.summary,{user_id:appliedUser,range:appliedRange});if(version!==generation)return;serverNow=new Date(data.server_now);byId('ladTotal').textContent=data.untouched.total;byId('ladNew').textContent=data.untouched.new;byId('ladTransfer').textContent=data.untouched.fresh_transfer;byId('ladTaskTotals').innerHTML=`<span>Scheduled <strong>${data.users.reduce((s,u)=>s+u.due,0)}</strong></span><span class="lad-total-completed">Completed Today <strong>${data.users.reduce((s,u)=>s+u.completed_today,0)}</strong></span><span class="lad-total-remaining">Remaining <strong>${data.users.reduce((s,u)=>s+u.remaining,0)}</strong></span>`;byId('ladRows').innerHTML=data.users.map(user=>`<tr id="ladUser-${user.id}"><td><div class="lad-person"><button type="button" class="lad-icon" data-expand="${user.id}" aria-expanded="false" title="Expand tasks" aria-label="Expand tasks for ${esc(user.name)}"><i class="fas fa-chevron-down"></i></button><span>${esc(user.name)}</span></div></td>${Object.keys(categories).map(key=>`<td><div class="lad-metrics">${countButton(user.id,'due',user.categories[key].due,key)}${countButton(user.id,'done',user.categories[key].done,key)}</div></td>`).join('')}<td>${countButton(user.id,'due',user.due)}</td><td>${countButton(user.id,'completed_today',user.completed_today)}</td><td>${countButton(user.id,'remaining',user.remaining)}</td></tr>`).join('')||'<tr><td colspan="9" class="lad-message">No sales users.</td></tr>';await untouched(1,version);}catch(error){byId('ladError').textContent=error.message;byId('ladError').hidden=false;byId('ladRows').innerHTML='<tr><td colspan="9" class="lad-message">Data unavailable</td></tr>';byId('ladUntouched').innerHTML='<tr><td colspan="8" class="lad-message">Data unavailable</td></tr>';}finally{byId('ladApply').disabled=false;}}
    async function expand(user,bucket='due',category='',page=1){const version=generation;document.querySelectorAll('.lad-expanded').forEach(el=>el.remove());document.querySelectorAll('[data-expand]').forEach(el=>el.setAttribute('aria-expanded','false'));const key={user,bucket,category,page};expanded=key;const row=document.createElement('tr');row.className='lad-expanded';row.innerHTML='<td colspan="9" class="lad-expand-cell"><div class="lad-message">Loading...</div></td>';byId('ladUser-'+user).after(row);byId('ladUser-'+user).querySelector('[data-expand]').setAttribute('aria-expanded','true');try{const data=await get(urls.tasks,{user_id:user,bucket,category,page});if(version!==generation||expanded!==key)return;row.innerHTML=`<td colspan="9" class="lad-expand-cell"><div class="lad-expanded-head"><strong>${esc(categories[category]||'All Tasks')} · ${esc(bucketLabels[bucket])}</strong></div><div class="lad-scroll"><table class="lad-table"><thead><tr><th>Customer</th><th>Mobile</th><th>Activity</th><th>Scheduled At</th><th>Status / Outcome</th><th>Completed At</th><th>View</th></tr></thead><tbody>${data.data.map(item=>`<tr><td>${esc(item.customer)}</td><td>${esc(item.phone||'-')}</td><td>${esc(categories[item.category])}</td><td>${esc(date(item.scheduled_at))}</td><td>${esc(item.status)}<small>${esc(item.outcome||'')}</small></td><td>${item.done?esc(date(item.completed_at)):'-'}</td><td>${eye(item.lead_id)}</td></tr>`).join('')||'<tr><td colspan="7" class="lad-message">No matching tasks.</td></tr>'}</tbody></table></div><div class="lad-pager"></div></td>`;pager(row.querySelector('.lad-pager'),data,p=>expand(user,bucket,category,p));}catch(error){if(expanded===key)row.innerHTML=`<td colspan="9" class="lad-error">${esc(error.message)}</td>`;}}
    async function details(id){const dialog=byId('ladDetails'),body=byId('ladDetailsBody');body.innerHTML='<div class="lad-message">Loading...</div>';dialog.showModal();try{const data=await get(urls.details,{lead_id:id});body.innerHTML=`<h3>${esc(data.customer)}</h3>`+[['Contact',data.contact],['Customer Profiling',data.profile],['Requirements',data.requirements],['Latest Sales Update',data.sales_update]].map(([title,fields])=>`<h3>${title}</h3><div class="lad-detail-grid">${Object.entries(fields||{}).map(([key,value])=>`<div><small>${esc(key)}</small><strong>${esc(value)}</strong></div>`).join('')}</div>`).join('')+`<h3>Remark History</h3>${(data.remark_history||[]).map(item=>`<div class="lad-history">${esc(item.remark||item.text||item.description||'')}<small>${esc(item.user||item.actor||'')} ${esc(item.recorded_at?date(item.recorded_at):'Unknown')}</small></div>`).join('')}`;body.scrollTop=0;}catch(error){body.textContent=error.message;}}
    byId('ladApply').onclick=load;byId('ladClose').onclick=()=>byId('ladDetails').close();document.querySelector('.lad-page').addEventListener('click',event=>{const lead=event.target.closest('[data-lead]');if(lead){details(lead.dataset.lead);return;}const arrow=event.target.closest('[data-expand]');if(arrow){if(expanded?.user===arrow.dataset.expand){document.querySelectorAll('.lad-expanded').forEach(el=>el.remove());expanded=null;arrow.setAttribute('aria-expanded','false');}else expand(arrow.dataset.expand);return;}const count=event.target.closest('[data-user]');if(count)expand(count.dataset.user,count.dataset.bucket,count.dataset.category);});load();
})();
</script>
@endpush
