@extends(auth()->user()?->isFinanceManager() && !auth()->user()?->isAdmin() ? 'finance-manager.layout' : 'layouts.app')
@section('title', 'Builder Invoice '.$invoice->invoice_number)
@section('page-title', 'Builder Invoice')
@push('styles')<link rel="stylesheet" href="{{ asset('css/post-sales.css') }}">@endpush
@section('content')
@php $money=fn($value)=>'Rs '.number_format((float)$value,2); @endphp
<div class="ps-shell">
    <header class="ps-topbar"><a class="ps-btn" href="{{ route('post-sales.index',['tab'=>'builder-desk']) }}"><i class="fas fa-arrow-left"></i></a><div><div class="ps-title">{{ $invoice->invoice_number }}</div><small>{{ $invoice->buyer_name }} · Revision {{ $invoice->revision_no }}</small></div><span class="ps-badge {{ $invoice->status }}" style="margin-left:auto">{{ str($invoice->status)->headline() }}</span>@if($invoice->status==='issued')<a class="ps-btn blue" href="{{ route('post-sales.invoices.download',$invoice) }}"><i class="fas fa-download"></i> Download</a>@endif</header>
    @if($invoice->status!=='draft')<div class="ps-mail-lock"><i class="fas fa-lock"></i> Issued invoice locked hai. Save karne par revision reason mandatory hoga aur current version history mein preserve rahega.</div>@endif
    <form class="ps-panel" method="POST" action="{{ route('post-sales.invoices.update',$invoice) }}" data-loading>@csrf @method('PUT')
        <div class="ps-form-grid">
            <div class="ps-field"><label>Invoice Date</label><input class="ps-input" type="date" name="invoice_date" value="{{ old('invoice_date',optional($invoice->invoice_date)->format('Y-m-d')) }}" required></div><div class="ps-field"><label>Due Date</label><input class="ps-input" type="date" name="due_date" value="{{ old('due_date',optional($invoice->due_date)->format('Y-m-d')) }}"></div>
            <div class="ps-field"><label>Seller Name</label><input class="ps-input" name="seller_name" value="{{ old('seller_name',$invoice->seller_name) }}" required></div><div class="ps-field"><label>Seller GSTIN</label><input class="ps-input" name="seller_gstin" value="{{ old('seller_gstin',$invoice->seller_gstin) }}"></div><div class="ps-field wide"><label>Seller Address</label><textarea class="ps-textarea" name="seller_address">{{ old('seller_address',$invoice->seller_address) }}</textarea></div>
            <div class="ps-field"><label>Builder / Buyer</label><input class="ps-input" name="buyer_name" value="{{ old('buyer_name',$invoice->buyer_name) }}" required></div><div class="ps-field"><label>Buyer GSTIN</label><input class="ps-input" name="buyer_gstin" value="{{ old('buyer_gstin',$invoice->buyer_gstin) }}"></div><div class="ps-field wide"><label>Buyer Address</label><textarea class="ps-textarea" name="buyer_address">{{ old('buyer_address',$invoice->buyer_address) }}</textarea></div>
            <div class="ps-field"><label>Bank Name</label><input class="ps-input" name="bank_name" value="{{ old('bank_name',$invoice->bank_name) }}"></div><div class="ps-field"><label>Account Number</label><input class="ps-input" name="bank_account" value="{{ old('bank_account',$invoice->bank_account) }}"></div><div class="ps-field"><label>IFSC</label><input class="ps-input" name="bank_ifsc" value="{{ old('bank_ifsc',$invoice->bank_ifsc) }}"></div>
            <div class="ps-field"><label>GST Amount</label><input class="ps-input" type="number" step="0.01" min="0" name="gst_amount" value="{{ old('gst_amount',$invoice->gst_amount) }}"></div><div class="ps-field"><label>TDS Amount</label><input class="ps-input" type="number" step="0.01" min="0" name="tds_amount" value="{{ old('tds_amount',$invoice->tds_amount) }}"></div>
            <div class="ps-field wide"><label>Notes</label><textarea class="ps-textarea" name="notes">{{ old('notes',$invoice->notes) }}</textarea></div><div class="ps-field wide"><label>Terms</label><textarea class="ps-textarea" name="terms">{{ old('terms',$invoice->terms) }}</textarea></div>
            @if($invoice->status!=='draft')<div class="ps-field wide"><label>Revision Reason *</label><textarea class="ps-textarea" name="revision_reason" required minlength="5" placeholder="Why is this issued invoice being changed?">{{ old('revision_reason') }}</textarea></div>@endif
        </div><div style="display:flex;justify-content:flex-end;margin-top:12px"><button class="ps-btn primary" type="submit"><i class="fas fa-floppy-disk"></i> {{ $invoice->status==='draft'?'Save Draft':'Create Revision & Save' }}</button></div>
    </form>
    <section class="ps-sheet"><div class="ps-sheet-head"><strong>Invoice Items</strong><span class="meta">Subtotal {{ $money($invoice->subtotal) }}</span></div><div class="ps-table-wrap" style="max-height:320px"><table class="ps-table" style="min-width:850px"><thead><tr><th>#</th><th>Customer / Case</th><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td data-label="#">{{ $loop->iteration }}</td><td data-label="Customer">{{ $item->postSaleCase?->customer_name }}</td><td data-label="Description">{{ $item->description }}</td><td data-label="Qty">{{ $item->quantity }}</td><td data-label="Rate" class="ps-money">{{ $money($item->rate) }}</td><td data-label="Amount" class="ps-money">{{ $money($item->amount) }}</td></tr>@endforeach</tbody></table></div><div style="padding:12px;display:grid;justify-content:end;gap:5px;text-align:right"><div>Subtotal: <strong>{{ $money($invoice->subtotal) }}</strong></div><div>GST: <strong>{{ $money($invoice->gst_amount) }}</strong></div><div>TDS: <strong>- {{ $money($invoice->tds_amount) }}</strong></div><div style="font-size:17px">Net Receivable: <strong>{{ $money($invoice->net_receivable) }}</strong></div></div></section>
    @if($invoice->status==='draft')<form method="POST" action="{{ route('post-sales.invoices.issue',$invoice) }}" data-loading style="display:flex;justify-content:flex-end">@csrf<button class="ps-btn blue" type="submit" onclick="return confirm('Issue karne ke baad direct edit lock ho jayega. Continue?')"><i class="fas fa-file-circle-check"></i> Issue & Generate Invoice</button></form>@endif
    @if($invoice->revisions->isNotEmpty())<section class="ps-panel"><h3>Revision History</h3>@foreach($invoice->revisions as $revision)<div class="ps-invoice-row"><div class="main"><strong>Revision {{ $revision->revision_no }}</strong><small>{{ $revision->reason }} · {{ $revision->created_at->format('d M Y h:i A') }}</small></div></div>@endforeach</section>@endif
</div><div class="ps-loading" id="psLoading"><div class="ps-loading-box"><span class="ps-spinner"></span> Preparing invoice...</div></div>
@endsection
@push('scripts')<script>document.querySelectorAll('[data-loading]').forEach(f=>f.addEventListener('submit',()=>document.getElementById('psLoading').classList.add('show')))</script>@endpush
